name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
            ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - run: |
            git config --global user.name "bjornm82"
            git config --global credential.helper cache
            git clone https://${{secrets.ACCESS_TOKEN}}@github.com/bjornm82/dbt-snowboard
            cd dbt-snowboard
            sed -r -i "s/MARK_BRANCH','([0-9])+(.)+([0-9])+(.)+([0-9])+/MARK_BRANCH','0.0.6/g" snow/packages.yml
            git add .
            git commit -m "$(date)"
            git push