name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@main
      with:
        name: bjornm82/dbt-snowboard

    -
      name: update file and push to remote
        run: |
          echo "Test push commit to the remote in the workflow" >> test.txt
      git config --global user.name "bjornm82"
      git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      git add -A
      git commit -m "Update test.txt"
      git push
      name:
